### ISSUE TITLE
Crypto++ is accepting contributions

### ISSUE THREAD

**Issue by noloader** [mmoss/cryptopp#3]
Please mark this as a non-bug. Scons caught my eye, and I did not know how to reach out to you.

Wei Dai, the author of Crypto++, has basically turned control of the library over to the community. If you feel `scons` wold be a helpful addition, then please clone Wei's [Crypto++ GitHub](https://github.com/weidai11/cryptopp) and make a pull request.

The [latest GNUmakefile](http://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L300) has the following recipe. You should be able to use it to update your file list.

```
# Used to generate list of source files for Autotools, CMakeList and Android.mk
.PHONY: sources
sources:
    $(info Library sources: $(filter-out fipstest.cpp $(TESTSRCS),$(SRCS)))
    $(info )
    $(info Test sources: $(TESTSRCS))
```

You can use it to generate the source list because here's the rule to build the shared object. `LIBOBJS` is derived with `LIBOBJS := $(filter-out $(TESTOBJS),$(OBJS))`. 

```
libcryptopp.so: public_service | $(LIBOBJS)
    $(CXX) -shared -o $@ $(CXXFLAGS) $(GOLD_OPTION) $(LIBOBJS) $(LDLIBS)
```

Crypto++ 5.6.3 also squahed the Type Limits/Tautological compare warnings, so you will not need the `-Wtautological-compare` in:

```
env.AppendUnique(CCFLAGS = '-g -Wtautological-compare')
```

However, you _usually_ want `-DNDEBUG` for release builds. Its stops an occasional `assert` that's meant to provide additional debug information (and not crash a production program).

I'm one of the folks who have check-in privileges, so I can say for certain it will be checked-in if no one objects. The pull request ensure you will receive the proper credit for your contributions. I'm happy to drop the file by hand and perform the check-in if you want to avoid the recognition.

**Comment by mmoss** [comment]
Thanks for the heads-up! I was using SCONS a while back while working on a game-related side-project.  I found it to be pretty easy, at least compared to the build system at the time. I'll take a look and find some time to try and contribute. I know a few folks have found this version of the project to be helpful, and I'd love to contribute.

**Comment by noloader** [comment]
> I'll take a look and find some time to try and contribute. I know a few folks have found this version of the project to be helpful, and I'd love to contribute.

We'd love to see you at [Crypto++ | Contributors](https://github.com/weidai11/cryptopp/graphs/contributors).

A lot of projects shy away from community contributions. I have no problem with them because I'll work it into the testing regime. If there's a weak spot, then [cryptest.sh](https://github.com/weidai11/cryptopp/blob/master/cryptest.sh) on [20 or 30 platforms](http://cryptopp.com/wiki/Release_process#The_Mashup) will uncover it. In this case, I send you the feedback and you make another pull request to address the issue. If there's no complaints from the testing process, then we are done and everyone is happy :)

**Comment by mmoss** [comment]
No worries at all, the issue keeps it my radar :)

**Comment by mmoss** [comment]
I'm revisiting this. I'll bring myself up-to-date with the latest state of the project, and review the various forks of this project to find what'll best serve various folks. Thanks!
